[package]
name = "pitch-detector"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "AudioContext",
    "AnalyserNode",
    "MediaStreamAudioSourceNode",
    "Window",
    "Document"
]}
console_error_panic_hook = "0.1" 